# Generated by Django 4.1.6 on 2023-02-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_map_latitude_alter_map_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
